### ISSUE TITLE
Where to include xmds

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/HEP-ASTRO-COSMO#14]
http://www.xmds.org

package to use to solve ODEs, PDEs and SDEs. Used by people who work on BECs. Not sure if technically cosmology but some cosmologists use it.

Question is - should this be in the Cosmo section or not?
Thoughts?

**Comment by bradkav** [comment]
Hmmm...this doesn't look like it should be strictly in the cosmo section, but I don't know if we want to start a whole separate "general tools" section. 

How about keeping it in General Cosmology but adding a note in italics that says something like "Often used by X to solve Y" just so that there's some context?

**Comment by nikosarcevic** [comment]
yeah agreed, that is why I asked where to include this. Let's keep it in general cosmo and then see how this evolves. I will keep this issue open. Thanks, @bradkav !
